AVAILABLE_FRAMEWORKS = [
    "Django REST Framework",
    "Flask",
    "FastAPI",
    "Express.js",
    "Spring Boot",
    "Ruby on Rails",
    "Laravel",
    "ASP.NET Core",
    "Symfony",
    "CakePHP",
    "CodeIgniter",
    "Angular",
    "React",
    "Vue.js",
    "Svelte",
    "Next.js",
    "Nuxt.js",
    "Flutter",
    "React Native",
    "Ionic",
    "Xamarin",
    "Electron",
    "NestJS",
    "AdonisJS",
    "Hadoop",
    "Spark",
]